name: Publish Release

on:
  push:
    tags:
      - "*"

jobs:
  create_release:
    name: Create Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      # - name: Create XCFramework
      #   uses: unsignedapps/swift-create-xcframework@v2.3.0
      - name: Create GitHub Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          # files: |
          #   Cabinet.sha256
          #   Cabinet.zip
          #   CabinetCore.sha256
          #   CabinetCore.zip
          #   CabinetCoding.sha256
          #   CabinetCoding.zip
          #   CabinetCollections.sha256
          #   CabinetCollections.zip
          #   CabinetCrypto.sha256
          #   CabinetCrypto.zip
          #   CabinetFoundation.sha256
          #   CabinetFoundation.zip
          #   CabinetPartialTypes.sha256
          #   CabinetPartialTypes.zip
          #   CabinetPropertyWrappers.sha256
          #   CabinetPropertyWrappers.zip
          #   CabinetSwiftUI.sha256
          #   CabinetSwiftUI.zip
